### ISSUE TITLE
Displaying Console Logs should be optional parameter

### ISSUE THREAD

**Issue by c0dehu1k** [aerokube/selenoid-ui#181]
This is an Enhancement.

Console logs that we display on VNC screen should be made optional
99% of the time automation engineers/users goes to the page to see thr VNC only.

Very -actually very very few  times somebody needs to actually drill down to those logs.

IMHO
We should give us an option to hide that, IMHO, it does not make sense to show those running logs.. no body is going to get anything from it.

its once in a blue moon we need to debug, there is no point cluttering the space everytime i need to see VNC

its overloading system with unnecessary computational power (even if its very minimal). Let user decide he needs it or not. I am using selenoid from last 3 years. Never reached a time  where i need to deep dive in these logs

This was discussed in the aerokube Telegram channel along with @vania-pooh 

Thanks

**Comment by lanwen** [comment]
Cool, actually its already almost implemented - you can just expand vnc into fullscreen mode and log will be hidden (and not consume resources).

So in case, we will hide the log by default, should the vnc be kept in normal size or being maximized?

Also originally log was always there since first we didn't have vnc, but had logs. Maybe if everyone is using VNC containers now, worth to revisit that.

**Comment by ersuniljoshi** [comment]
@lanwen IMHO, Let UI defaults to maxmized VNC and then there should be a link to show logs (in case we need it).

**Comment by slavashmel** [comment]
totally agree with @ersuniljoshi. I've came with the same request. Our QA open vnc 50+ times a day and have to do additional click to expand it to fullscreen. While we try to expand it test is already finishes and have to add manual sleep to look something. It eats time and a little bit annoying)
And we don't use logs in VNC at all.
