### ISSUE TITLE
Adding additional information to the ui

### ISSUE THREAD

**Issue by f0rzer** [aerokube/selenoid-ui#352]
Selenoid-ui revision proposal
Add additional information about the state of the container
in point number 1 - information about the lifetime of the container, now it is visually difficult to understand how much the test is being performed
in point number 2 - ip / hostname of the node where the container is running
![1](https://user-images.githubusercontent.com/24559628/87760571-21443d00-c83a-11ea-955f-b5d5584fa59d.png)

these are not very important features, but it will help increase the comfort of use

**Comment by vania-pooh** [comment]
@f0rzer 
1) Аll this information should be first of all passed through Selenoid /status API.
2) Regarding container lifetime - shouldn't all these statistics be calculated on the tests side?
3) Don't get the used case of showing the hostname.

**Comment by f0rzer** [comment]
1. ok
2. duration of the test is fixed after its execution. it would be clear for me to see them in real time
3. could write what is a bad option to see the test execution environment (provided that it is not a cluster, but statically allocated nodes)?

**Comment by lanwen** [comment]
@f0rzer I think you want some kind of monitoring - for that better to go for a grafana panel https://github.com/aerokube/selenoid-grafana-example
I can understand the timer requirement - that would be nice really to track. But due to stateless nature of the selenoid and ui thats impossible to implement. And we don't want to bring a state in selenoid, as it would complicate things.
It's also hard to implement on the UI side, as it polls the state only when you're on the page.

I would close this issue, as it requires changing the state management in the selenoid, which we don't want to do and I don't really see the way ui can handle it on its own.

Maybe docker could provide us with this state, but still - have to be first exported by selenoid first then, so here is an issue there regarding docker stuff export in the status api https://github.com/aerokube/selenoid/issues/963
