### ISSUE TITLE
paging

### ISSUE THREAD

**Issue by kaylezhangzhaoLin** [aerokube/selenoid-ui#472]
Can you add videos paging function?

**Comment by vania-pooh** [comment]
Transferred to selenoid-ui.

**Comment by carl-pki** [comment]
![bd8d1db828ff23e0ef676df162a6b10](https://user-images.githubusercontent.com/85552832/193283151-8d44c894-ee2a-41ba-9e84-7527eb051eb6.jpg)
![6b650a4457d51aa5f303ec2d30887ba](https://user-images.githubusercontent.com/85552832/193283175-575fd74a-3e04-4e06-a38f-208740c069cb.jpg)

Hello,  [vania-pooh](https://github.com/vania-pooh), I have a question, do I need add the row to proxy the http request?

![image](https://user-images.githubusercontent.com/85552832/193284012-cce4191e-d2c6-4eed-8292-7ebf30f7fbba.png)

do I need add the code row to proxy the http question? because I want to request the Selenoid services.
